version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/testmyapp
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

snapshot:
  name_template: "{{ incpatch .Version }}"

release:
  replace_existing_artifacts: true
archives:
  - format: zip
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

chocolateys:
  - # Your app's package name.
    name: testmyapp

    package_source_url: https://github.com/Gjergj/testmyapp

    owners: Gjergj Ramku

    title: testmyapp

    authors: Gjergj Ramku
    url_template: "https://github.com/gjergj/testmyapp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    project_url: https://testmyapp.io

    copyright: 2024 Gjergj Ramku

    # App's license information url.
    license_url: https://github.com/Gjergj/testmyapp/blob/main/LICENSE

    require_license_acceptance: false

    project_source_url: https://github.com/Gjergj/testmyapp

    docs_url: https://github.com/Gjergj/testmyapp/blob/main/README.md

    bug_tracker_url: https://github.com/Gjergj/testmyapp/issues

    tags: "webhosting host webapp web tool devops build build-tool go"

    summary: Easily host and test your web app

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} installer package.
      Software to create fast and easy drum rolls.

    release_notes: "https://github.com/Gjergj/testmyapp/releases"

    api_key: "{{ .Env.CHOCOKEY }}"

    # The source repository that will push the package to.
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1

winget:
  - name: testmyapp
    publisher: gjergj
    short_description: Quickly test your web app
    license: MIT
    homepage: https://testmyapp.io/
    publisher_url: https://testmyapp.io/
    publisher_support_url: https://github.com/Gjergj/testmyapp/issues
    package_identifier: gjergj.testmyapp
    commit_author:
      name: testmyapp-bot
      email: gjergjiramku@gmail.com
    release_notes: "{{.Changelog}}"
    tags:
      - build
      - build-tool
      - devops
      - go
      - webapp
      - tool
      - webhost
      - web
    skip_upload: false
    repository:
      owner: gjergj
      name: winget-pkgs
      branch: "{{.ProjectName}}-v{{.Version}}"
      pull_request:
        enabled: false
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master