# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testmyapp < Formula
  desc "Cli for testmyapp.io"
  homepage "https://github.com/gjergj/testmyapp"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.5/testmyapp_Darwin_arm64.tar.gz"
    sha256 "27269cd5316e14a6565d28326b249da35cb70a5a9b983754dd9543a179115fc6"

    def install
      bin.install "task"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Gjergj/testmyapp/releases/download/v0.0.5/testmyapp_Darwin_x86_64.tar.gz"
    sha256 "d7838c83058c565bbce75b8d43f4afdba0370bf3f9a9021a532f3396e4ede46d"

    def install
      bin.install "task"
    end
  end
end
